USE BICYCLE_RENTAL_SYSTEM;
GO

CREATE ROLE ManagerRole;
CREATE ROLE StaffRole;
CREATE ROLE AnalystRole;
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA :: dbo TO ManagerRole;
GRANT SELECT ON SCHEMA :: dbo TO StaffRole;
GRANT INSERT, UPDATE ON dbo.Rental TO StaffRole;
GRANT INSERT, UPDATE ON dbo.Renter TO StaffRole;
GRANT INSERT, UPDATE ON dbo.Payment TO StaffRole;
GRANT SELECT ON SCHEMA :: dbo TO AnalystRole;
GO

CREATE LOGIN Sof WITH PASSWORD = 'StrongSecurePassword123!';
CREATE LOGIN Rami WITH PASSWORD = 'StrongSecurePassword123!';
CREATE LOGIN Nahim WITH PASSWORD = 'StrongSecurePassword123!';
GO

CREATE USER Sof FOR LOGIN Sof;
CREATE USER Rami FOR LOGIN Rami;
CREATE USER Nahim FOR LOGIN Nahim;
GO

ALTER ROLE ManagerRole ADD MEMBER Sof;
ALTER ROLE StaffRole ADD MEMBER Rami;
ALTER ROLE AnalystRole ADD MEMBER Nahim;
GO
